### PR TITLE
Expand post blast recovery

### PR DESCRIPTION
**Pull request by bkohrn**
This will expand options for post-blast recovery, and will clarify some related outputs.

### CODE REVIEW

**Comment by bkohrn** [comment]
I'm trying to be better about only making one set of changes in each branch, but we could do that.

**Comment by bkohrn** [comment]
My main concern is: that change is unrelated to the primary purpose of this branch.

**Comment by scottrk** [comment]
That's a good point. It doesn't change functionality, just the complexity of the code, so lower priority. Let's get this out and merge in a fix later.

**Comment by bkohrn** [comment]
I have one more branch I want to finish before we go to v2.0.0.  Actually, if we're going to do a v1.1.0 release, we should do that before we finish merging this branch.

**Pull request merged**
